services:
  ultimatetv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ultimatetv
    ports:
      - "5173:80"
    restart: unless-stopped
    environment:
      - TZ=America/Sao_Paulo
    networks:
      - tv-network

networks:
  tv-network:
    driver: bridge