server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    # Compressão Gzip agressiva para aliviar a rede da TV
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 1000;

    # Suporte a SPA: Qualquer rota não encontrada cai no index.html
    location / {
        # --- CONTROLE DE ACESSO (ALLOWLIST) ---
        allow 10.0.7.4;
        allow 10.0.7.5;
        allow 10.0.7.6;
        allow 10.0.7.7;
        allow 10.0.7.20;
        allow 10.0.7.32;
        allow 127.0.0.1;
        deny all;
        # --------------------------------------
        
        try_files $uri $uri/ /index.html;
    }

    # Cache longo para arquivos estáticos (CSS, JS, Logos, Fontes)
    location ~* \.(?:ico|css|js|gif|jpe?g|png|woff2?|eot|ttf|svg|mp4)$ {
        expires 6M;
        access_log off;
        add_header Cache-Control "public, max-age=15552000, immutable";
    }

    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }

    # Custom Error Page 403 (Dispositivo Não Autorizado)
    error_page 403 /403.html;
    location = /403.html {
        root /usr/share/nginx/html;
        allow all;
    }
}